#!/bin/bash

RBMM_JAVA=${RBMM_JAVA:-"rbmm-java"}

cd /rbmm-nodejs
sed -e "s|^ *url: .*$|url: \"http://$RBMM_JAVA:8080/CLOUD4All_RBMM_Restful_WS/RBMM/runJSONLDRules\",|" -i lib/RuleBasedMatchMaker.js

chown gpii /rbmm-nodejs -R
export NODE_ENV=development
su gpii -c "node bin/ruleBasedMatchMaker"
